### ISSUE TITLE
Implement bookmarking feature

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#102]

**Comment by cmurray191** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/102?planning-poker) with ZenHub @Fattimo

**Comment by Fattimo** [comment]
need bookmarking screen

**Comment by Fattimo** [comment]
what should the bookmark bubble on teh home page look like if there are not enough bookmarks
