### ISSUE TITLE
Add audiobook feature

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#104]
- [ ] Reader can toggle audiobook using button on sidebar
- [ ] When audiobook is on, the audio begins playing from the current page and every time the reader flips to another page, the audio for that page will begin playing
- [ ] When both pages are being displayed side-by-side, the audio should begin from the left page and automatically switch to the right page once the left page's audio is finished
- [ ] If reader clicks on any navigation buttons that give them the option to read with audio or without audio, the audio toggle has the correct setting when the reading screen is loaded. Audio automatically begins playing if they chose to read with audio
- [ ] When audio is toggled on, a pause/play button appears on the sidebar that can be used
- [ ] Audio can be skipped/begin playing from any desired place on the page as described in #152 

Audio can be accessed from here:
`https://brainy-literacy-assets.s3.amazonaws.com/audio/awa/awa_<chapterNumber>.mp3`

Timestamps for each chapter are in teams under the "Audio" folder

**Comment by cmurray191** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/104?planning-poker) with ZenHub @Fattimo

**Comment by Fattimo** [comment]
@joe-lazzarini would it be possible to parse the teams doc and have starting timestamps for each page + duration of each page inside of the `pages` field?

so updated pages would end up looking something like:
```
"pages": {"1": {"page": 1, "chapter": 1, "ts": seconds, "duration": seconds}, ...
```
If ts can be a number in seconds and duration also a number in seconds that would be great. ts represents the starting time of that particular page.

**Comment by Fattimo** [comment]
Something to look out for is that i have no idea what the timestamps inside of the teams doc is supposed to represent, since it doesn't make sense that page 1-1 (the first page of the book) starts at time 2:08

**Comment by cmurray191** [comment]
@joe-lazzarini I just went through the timestamps document and made sure everything was consistent with the audio. The timestamps for each page represent the end of the page, not the beginning of the page.

**Comment by joe-lazzarini** [comment]
This all sounds good.
