### ISSUE TITLE
page 43 

### ISSUE THREAD

**Issue by Fattimo** [Fattimo/hear-a-tale-awakening_JIB1339#120]
https://hear-a-tale-awakening-pl895qe79-fattimo.vercel.app/page/43

chapter 9 page 7 does not exist

**Comment by Fattimo** [comment]
same with page 20, page 5 chapter 5
<img width="960" alt="image" src="https://user-images.githubusercontent.com/57023314/158034112-95bc0e4d-c642-46de-b780-6ce5c9451a28.png">

**Comment by Fattimo** [comment]
seems to only happen around chapter borders

**Comment by joe-lazzarini** [comment]
Pretty sure this was a merge error. Rerunning script fixed it.
