### ISSUE TITLE
Parse French translations

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#149]
There are two files to look at in Teams under definitions -> French.
Single_Words_French contains translations of individual French words.
Phrases_French contains translations of entire French phrases.

When the reader clicks on a french word or phrase, the corresponding translation will be cued. This will need to be handled differently than definitions. If the word is part of a phrase, then the entire phrase will need to be highlighted and its translation will be cued. However, if it is just a single word that is not part of an entire phrase, then just the word is highlighted and the translation of the word is cued. This may be tricky because some of the words appear both inside of a phrase and outside of a phrase.

**Comment by cmurray191** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/149?planning-poker) with ZenHub @joe-lazzarini

**Comment by joe-lazzarini** [comment]
@Fattimo Let me know how you want the phrases parsed. I am parsing the French words along with the English ones
