### ISSUE TITLE
Change audio button(s) on quiz screen

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#151]
- [ ] One button cues audio for the word being quizzed
- [ ] Other button cues audio for the definition

~~This is blocked by #145~~
Design is on Figma (first Quiz Screen)

**Comment by cmurray191** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/151?planning-poker) with ZenHub @Fattimo

**Comment by Fattimo** [comment]
the design does not match the current product. there are no buttons to move forward with the quiz or exit the quiz. there is limited space to implement the designs as is
