### ISSUE TITLE
Fix audio overlay issues

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#165]
The definition audio should stop playing if:
a. The popup is closed
b. The reader takes a quiz
c. The reader leaves the reading screen using the buttons on the sidebar
d. The reader begins playing the audio for the book

The book audio should stop playing if:
a. The reader cues the audio for an individual word
b. The reader cues audio for a definition. This shouldn't be able to happen, but it currently can. See issue #166  

Individual word audio should stop playing if:
a. The reader cues audio for definition
b. The reader starts the audiobook

**Comment by Fattimo** [comment]
under what circumstances is `The reader leaves the reading screen using the buttons on the sidebar` a thing?
