### ISSUE TITLE
Add French translations feature

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#168]
When the reader clicks on a French word or phrase, the corresponding translation audio will be cued. This will need to be handled differently than definitions.

- If the word is part of a phrase, then the entire phrase will need to be highlighted and its translation will be cued. 

- If it is just a single word that is not part of an entire phrase, then just the word is highlighted and the translation of the word is cued. This may be tricky because some of the words appear both inside of a phrase and outside of a phrase.

When a French translation is clicked again while highlighted, the text for the translation should appear in a popup (like what happens for definitions). However,

- The translation popup should be a different color than the normal definition popup
- The option to take a quiz should not be there

@joe-lazzarini has already done some work on parsing the French translations from the document we were given.

Audio can be grabbed from here:
`https://brainy-literacy-assets.s3.amazonaws.com/audio/french/<word/phrase>.mp3`

Example for single word:
https://brainy-literacy-assets.s3.amazonaws.com/audio/french/bonfils.mp3

Example for phrase:
https://brainy-literacy-assets.s3.amazonaws.com/audio/french/bon_garcon.mp3

**Comment by Fattimo** [comment]
@joe-lazzarini for french things, we need to generate txt files differently and store the definitions in the database differently.

Database shape:
```
words: [string]
definition: string
french: boolean
```
Basically, the same as before, except add a boolean for french and omit the first letter field

For txt file generation:

This is only relevant to french phrases. When a french phrase is matched, delete the spaces in between the phrase and replace them with `&fr;`

**Comment by cmurray191** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/168?planning-poker) with ZenHub @Fattimo @joe-lazzarini
