### ISSUE TITLE
Data tracking for DAP

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#177]
The following data will need to be shared with the data analytics platform:

- Every word the user has cued (clicked on to hear the individual word audio)
- Highest number of consecutive correct first answers on a quiz for any word that has been quizzed - i.e. the number of silver stars (or gold stars if the number of gold stars >= number of silver stars)
- Total number of correct answers
- Total number of incorrect answers
- Total number of correct answers for a word
- Total number of incorrect answers for a word
- Most recent 3 dates that the app was accessed

**Comment by Fattimo** [comment]
must all of this data be relational to a user? is pii an issue? (personal identifying information tied to the user)

@joe-lazzarini important for detailed design section

**Comment by cmurray191** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/177?planning-poker) with ZenHub @Fattimo

**Comment by Fattimo** [comment]
@cmurray191 for 

"Total number of correct answers on a quiz (for each quizzed word)
Total number of incorrect answers on a quiz (for each quizzed word)"

is this referring to a per word or a per quiz basis?

For example, let's say I click on the word 'spooky' and take a quiz on it. Then, later on, I click on 'spooky' again and take another quiz on it. Would there be 2 different documents within our database for the 'spooky' quiz associated with my user account, or is there one document cumulatively tracking the total number of 'spooky' questions I've gotten correct/incorrect?

Additionally, how should I deal with data tracking for unauthed users? should I insert documents within the database anonymously (i.e. not associated with a user record)? How does this interface with my above concern if it is cumulatively tracking? Should we not track data on unauthed users?

**Comment by cmurray191** [comment]
@Fattimo The wording on that was really weird. I just updated the list. There will be a running count of the total number of correct and incorrect answers overall (specific words/quizzes don't matter) as well as a running count of total correct/incorrect answers for each word (across all quizzes on that word).

For the second point, don't track data for unauthed users.
