### ISSUE TITLE
Update review screen to include data linked to a user

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#192]
This is an extension of #177 that will enable the user to see the information that is being tracked.

**Comment by cmurray191** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/192?planning-poker) with ZenHub @Fattimo

**Comment by Fattimo** [comment]
@isabellamoak @vstevens14 woudl it be possible to make the review screen more reflective of the data we are actually tracking in #177?

**Comment by Fattimo** [comment]
given that the dap is only relevant for authed users, should the review tab be inaccessible to those who are not authed?
