### ISSUE TITLE
Change icon in top left from the current cartoon character to an image of Kate Chopin's face

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#200]

**Comment by Fattimo** [comment]
@cmurray191 @isabellamoak @vstevens14 need a design/resource for a kate chopin face

**Comment by Fattimo** [comment]
if one slide on the figma could reflect this that would be sufficient

**Comment by cmurray191** [comment]
@Fattimo Just added the picture to the figma on the home screen
