### ISSUE TITLE
Include images of Kate Chopin on background page under the 'Setting' heading

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#60]
Dr Evans added 8 images to the Dropbox under [Artwork -> Chopin pictures](https://www.dropbox.com/home/1339%20Awakening/ARTWORK/Chopin_Pictures)
The images should be scrollable in the order they are found in the dropbox folder

**Comment by Fattimo** [comment]
Where can I find the text to include on this page?
