### ISSUE TITLE
Add tutorial page that can accessed from home screen

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#63]

**Comment by Fattimo** [comment]
Are static images good enough for the tutorial screen? Should I use the static images in the figma, or should we replace those with actual text from the novel? @cmurray191 @isabellamoak @vstevens14

**Comment by cmurray191** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/63?planning-poker) with ZenHub @Fattimo
