### ISSUE TITLE
Implement definitions audio

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#83]
- [x] When reader clicks on a word after it is cued, the popup displays the word (definitions not yet ready)
- [x] Popup has an icon to play the audio for the definition
- [ ] When the reader clicks on the audio icon, the audio for the definition is played
- [x] Popup has an icon to begin a quiz
- [x] After returning from a quiz, the popup is still there and the word is still highlighted
- [x] When the reader is done reading the definition, they can press the x button to close the popup
- [x] After closing the popup, the highlighted word is no longer highlighted

~~For right now, the focus is going to be on the audio for the definitions, as the text still needs to be processed.~~

**Comment by Fattimo** [comment]
can you link the sources for definitions text here?

**Comment by Fattimo** [comment]
can you link the sources for definitions audio?

**Comment by cmurray191** [comment]
The definition audio can be accessed as follows:
https://brainy-literacy-assets.s3.amazonaws.com/audio/defs/<letter>/<word>%2B.mp3

The letter should be capitalized.
As of right now, only letters A,B,C,D,E,F,P,Q,R have definition audio.

**Comment by cmurray191** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/83?planning-poker) with ZenHub @Fattimo

**Comment by Fattimo** [comment]
The definition audio link has authorization limitations. Trying to access the audio src from that link will throw a 403 forbidden error. @cmurray191

**Comment by Fattimo** [comment]
> The definition audio link has authorization limitations. Trying to access the audio src from that link will throw a 403 forbidden error. @cmurray191

providing an example url that is accessible would help

**Comment by Fattimo** [comment]
> > The definition audio link has authorization limitations. Trying to access the audio src from that link will throw a 403 forbidden error. @cmurray191
> 
> providing an example url that is accessible would help

i.e. compare https://brainy-literacy-assets.s3.amazonaws.com/audio/incorrect_answer_sound.mp3 this link and https://brainy-literacy-assets.s3.amazonaws.com/audio/defs/P/property%2B.mp3 this one

**Comment by Fattimo** [comment]
does this ticket include implementing the updated figma and the features of being able to play word audio and definition audio from the quiz screen?

**Comment by cmurray191** [comment]
> > > The definition audio link has authorization limitations. Trying to access the audio src from that link will throw a 403 forbidden error. @cmurray191
> > 
> > 
> > providing an example url that is accessible would help
> 
> i.e. compare https://brainy-literacy-assets.s3.amazonaws.com/audio/incorrect_answer_sound.mp3 this link and https://brainy-literacy-assets.s3.amazonaws.com/audio/defs/P/property%2B.mp3 this one

This should be resolved now. Try this for example:
https://brainy-literacy-assets.s3.amazonaws.com/audio/defs/A/absolutely%2B.mp3

It's the same format as the link you shared. Both of those should work as well as all other definitions.

**Comment by cmurray191** [comment]
> does this ticket include implementing the updated figma and the features of being able to play word audio and definition audio from the quiz screen?

No I will add another one for that. The current design on figma needs some work because we won't have audio for all of the words in the quiz and we only want the reader to be playing the audio for the word being quizzed anyway.

**Comment by Fattimo** [comment]
absolutely exists on page 31 or 32 (i think 32)

**Comment by Fattimo** [comment]
also works on property
