### ISSUE TITLE
Extract definition text from word document

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#84]
~~The document has been moved to teams files (Definitions to GT Part 1 updated). Another file for part 3 has also been added, although we do not currently have part 2. **The part 3 document has a few lines containing red text indicating that the definition should be changed from what was in the part 1 document**~~

The folder "Definitions" in teams has two subfolders; the English subfolder contains the Part 1 document that we have already completed and the cleaned document containing all of the remaining definitions.

**Comment by Fattimo** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Engineering---Team-1339-615210023f07720011a452da/issues/Fattimo/hear-a-tale-awakening_JIB1339/84?planning-poker) with ZenHub @joe-lazzarini

**Comment by Fattimo** [comment]
Acceptance criteria:
1. Parse through words in the document
2. Create a document within the mongodb server for each word
3. The document should at minimum have the word, definition, and first letter of the word within it
4. Index by the word and first letter https://docs.mongodb.com/manual/indexes, https://docs.mongodb.com/manual/indexes/#multikey-index
5. Recommend the shape of the document looks like this:

```
{
_id: default mongodb pk,
words: [string],
definition: string,
first_letter: string, 
}
```

**Comment by Fattimo** [comment]
@cmurray191 the linked document is not complete
