### ISSUE TITLE
Fix word highlighting persisting after definition is cued

### ISSUE THREAD

**Issue by cmurray191** [Fattimo/hear-a-tale-awakening_JIB1339#85]
If the reader cues the definition, the word stays highlighted until another word is clicked. This should be changed to the highlighting going away after a small delay of ~2s

**Comment by Fattimo** [comment]
how is a reader supposed to have enough time to queue a quiz then? Or read the definition?

**Comment by Fattimo** [comment]
see pr, there was a mistake in my expected behavior, but this should solve the issue. The word will stay highlighted as long as the definition stays active. If a different word is queued or the x button is pressed, then the word no longer stays highlighted.
